backend:
  name: github
  repo: lozette/playbook
  branch: main
media_folder: "_images"
publish_mode: editorial_workflow
show_preview_links: true
collections:
  - name: "guides"
    label: "Guides"
    folder: "guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
